const express = require('express')
const cors = require('cors')
const dotenv = require('dotenv')
const { initSchema } = require('./database/data-source')
const consultationsRouter = require('./modules/consultations/consultations.routes')
const insuranceRouter = require('./modules/insurance/insurance.routes')
const pharmacyRouter = require('./modules/pharmacy/pharmacy.routes')
const deliveryRouter = require('./modules/delivery/delivery.routes')
const ussdRouter = require('./integrations/ussd/ussd.routes')
const prescriptionsRouter = require('./modules/prescriptions/prescriptions.routes')
const authRouter = require('./modules/auth/auth.routes')

dotenv.config()

const app = express()
app.use(cors({ origin: '*'}))
app.use(express.json())

app.get('/api/health', (req, res) => res.json({ ok: true }))
app.use('/api/consultations', consultationsRouter)
app.use('/api/insurance', insuranceRouter)
app.use('/api/pharmacy', pharmacyRouter)
app.use('/api/delivery', deliveryRouter)
app.use('/api/ussd', ussdRouter)
app.use('/api/prescriptions', prescriptionsRouter)
app.use('/api/auth', authRouter)

const port = Number(process.env.PORT || 4000)
app.listen(port, () => {})
initSchema().catch(() => {})